/* Generated By:JavaCC: Do not edit this line. MyABGrammarConstants.java */
package abgrammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyABGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 7;
  /** RegularExpression Id. */
  int B = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"*\"",
    "\"1\"",
  };

}
