/* Generated By:JavaCC: Do not edit this line. JustSimpleGrammarConstants.java */
package mni1670;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JustSimpleGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int NO_RETURN_TYPE = 12;
  /** RegularExpression Id. */
  int INT_TYPE = 13;
  /** RegularExpression Id. */
  int BOOLEAN_TYPE = 14;
  /** RegularExpression Id. */
  int OPEN = 15;
  /** RegularExpression Id. */
  int CLOSE = 16;
  /** RegularExpression Id. */
  int SEPERATOR = 17;
  /** RegularExpression Id. */
  int STATEMENT_CLOSE = 18;
  /** RegularExpression Id. */
  int ASSIGNMENT = 19;
  /** RegularExpression Id. */
  int BRACE_OPEN = 20;
  /** RegularExpression Id. */
  int BRACE_CLOSE = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<DIGIT>",
    "\".\"",
    "<NUMBER>",
    "<LETTER>",
    "<IDENTIFIER>",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"program\"",
    "\"byref\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
  };

}
